import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import fs from 'fs';
import path from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

let copyFilesPlugin = {
	name: 'copy-files',
	setup(build) {
	  build.onEnd(() => {
		// Files to copy
		const filesToCopy = ['data.json', 'manifest.json', 'styles.css'];
  
		filesToCopy.forEach((file) => {
		  const srcPath = path.resolve(file);
		  const destPath = path.resolve('./dist', file);
		  
		  // Check if the file exists and copy it to dist
		  if (fs.existsSync(srcPath)) {
			fs.copyFileSync(srcPath, destPath);
			console.log(`${file} copied to dist/`);
		  } else {
			console.log(`${file} not found, skipping.`);
		  }
		});
	  });
	},
  };

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: './dist/main.js',
	loader: {   
		'.ttf': 'base64', 
	},
	plugins: [copyFilesPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
